workflows:
  ios-build:
    name: iOS Build for TestFlight
    environment:
      vars:
        XCODE_WORKSPACE: "JatimPresences.xcworkspace"
        XCODE_SCHEME: "JatimPresences"
        APP_STORE_CONNECT_TEAM_ID: "W98H4R8DD7"
        APP_STORE_CONNECT_APPLE_ID: "muhammaddafiramadhan@gmail.com"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install --force
          
          cd node_modules/react-native/scripts
          chmod +x ios-install-third-party.sh
          ./ios-install-third-party.sh

          cd third-party/glog-0.3.5
          rm -f missing
          autoreconf -fiv || true
          sed -i '' 's/armv7/arm64/g' ../../ios-configure-glog.sh
          sed -i '' 's/return ac_fn_c_try_compile/echo skip compile test; return 0/' configure

          cd ../../
          chmod +x ios-install-third-party.sh
          ./ios-install-third-party.sh

          cd ../../../ios
          pod install --repo-update
      - name: Build iOS app
        script: |
          xcodebuild -workspace "ios/$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath $CM_BUILD_DIR/JatimPresences.xcarchive archive

          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/JatimPresences.xcarchive \
          -exportOptionsPlist ios/exportOptions.plist \
          -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - build/ios/ipa/*.ipa
