workflows:
  ios-build:
    name: iOS Build (IPA only, no upload)
    environment:
      vars:
        XCODE_WORKSPACE: "JatimPresences.xcworkspace"
        XCODE_SCHEME: "JatimPresences"
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install --force

          cd node_modules/react-native/scripts
          chmod +x ios-install-third-party.sh
          ./ios-install-third-party.sh

          cd third-party/glog-0.3.5
          rm -f missing
          autoreconf -fiv || true
          sed -i '' 's/armv7/arm64/g' ../../ios-configure-glog.sh
          sed -i '' 's/return ac_fn_c_try_compile/echo skip compile test; return 0/' configure

          cd ../../
          chmod +x ios-install-third-party.sh
          ./ios-install-third-party.sh

          cd ../../../ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod install --repo-update
      - name: Build iOS app (no signing)
        script: |
          cd ios
          xcodebuild clean

          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/JatimPresences.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/JatimPresences.xcarchive \
            -exportPath $CM_BUILD_DIR/ipa \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa